### ISSUE TITLE
Support `neuro ls` operations without scheme

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1035]
User's confused:
```
$ n ls
nmrc  public  test
$ n ls test
ERROR: Invalid storage scheme 'file://' (only 'storage://' is allowed)
```

**Comment by serhiy-storchaka** [comment]
If makes `storage:` optional on `ls`, then why not make it optional in `rm` and `mv` which also work only with storage URIs? Then the only storage command which require `storage:` will be `cp`. This may confuse users. But there is other issue. `rm` and `mv` support glob patterns. For example you can run `neuro storage rm storage:test/**/*.out` to remove all files with extension `.out` in the "test" directory and its subdirectories. This works without additional quoting because it is unlikely that you have directory "storage:test" in the current directory. But if omit `storage:`, the result can be different, depending on whether there is a directory "test" in your current dicrectory. You will need to quote the pattern: `neuro storage rm 'test/**/*.out'`.

If make the only `ls` special, this will bring the users question: "Why?"

**Comment by ayushkovskiy** [comment]
Again, working with the platform, I realized that the prefix `storage:` in `neuro ls` commands is redundant.

How about we omit `storage:` on all `neuro storage` operations AND split `neuro cp` to 2 new commands: `neuro upload` and `neuro download` (or `neuro cp --upload` and `neuro cp --download`, or `neuro cp --put` and `neuro cp --get` -- the naming is discussable). The idea is that we get the syntax where the user doesn't need to specify `storage:` all the time.

**Comment by asvetlov** [comment]
Read the message above about path pattern unfolding

**Comment by serhiy-storchaka** [comment]
There was discussed an idea about supporting Amazon S3, so we could use `neuro cp s3:... storage:...` and `neuro cp storage:... s3:...`. And once we implement transferring files between the storage and Amazon S3, we could easily implement transferring files between local disk and Amazon S3: `neuro cp s3:... file:...` and `neuro cp file:... s3:...` (although there are existing tools for this). And we can repeat the same for the Google Cloud Storage. So we will end either with a dozen of different commands for transferring files for every pair of kinds of storages, or with specifying the king of storage by scheme.

**Comment by ayushkovskiy** [comment]
OK the argument with supporting different types of storage convinces me.

**Comment by asvetlov** [comment]
Right!
What we could improve right now is adding `st:` alias for `storage:` scheme; it can help people who are typing not very fast :)
