### ISSUE TITLE
Proposal: make `neuro rm --glob` not to fail when it meets a directory

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1044]
On Unix, when using filename pattern, the `rm` operation actually removes files (maybe not always all of them?) even if has met a directory:
```
$ ls data/
1  2  dir
$ rm data/*
rm: cannot remove 'data/dir': Is a directory
$ ls data/
dir
```
Neuro client fails and does not remove the files:
```
$ n ls storage:data
02fff10d.tmp  25104231.tmp  698f8cf1.tmp  72ce2799.tmp  906421cd.tmp  9b65faae.tmp  data  eb59d70e.tmp
$ neuro rm --glob storage:data/*
ERROR: I/O Error ([Errno 21] Is a directory, use recursive remove: 'storage://test2/data/data')
$ n ls storage:data
02fff10d.tmp  25104231.tmp  698f8cf1.tmp  72ce2799.tmp  906421cd.tmp  9b65faae.tmp  data  
```
Maybe we should also print errors if `--glob` met a directory, but skip them and do remove other files.

**Comment by serhiy-storchaka** [comment]
No need to specify `--glob`, it is default.

**Comment by ayushkovskiy** [comment]
> No need to specify --glob, it is default.

1. Then let's drop this parameter?
2. Maybe we still should consider fixing the described behaviour?

**Comment by asvetlov** [comment]
I think the current behavior is safer than proposed.
If you want to remove a directory -- use `--recursive`.
What is the use case for removing files but failing on dirs?

**Comment by serhiy-storchaka** [comment]
It makes sense. Posix `rm` reports errors, but continue to remove other arguments.

**Comment by asvetlov** [comment]
What is the behavior for posix deletion of a directory that contains non-empty folders inside?
Try to answer before running a command to check.

**Comment by serhiy-storchaka** [comment]
Posix `rm` does not remove a directory. There is a special command `rmdir` for removing an empty directory. `rm` itself reports errors for every argument which it can not proceed (because it is a directory, does not exist, not accessible, or in read-only directory) and continue to remove others. Same for `ls`, `mkdir`, `cp`, `mv`.

It makes sense because you can run `rm -rf results.tar output/*.res` in your script and will clean up `output/*.res` even if `results.tar` does not exist.
