### ISSUE TITLE
Consider making `neuro ps` closer to analogue tools

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/platform-client-python#1060]
`neuro ps` is slightly different from Unix `ps` and analogue tools. Let's look closely at other tools and consider some changes. For example:

* By default, show jobs of the current user only.
* Use `neuro ps -a` to show own and shared running jobs.
* Use `neuro ps -A` to show all available jobs.
* Use user name instead of `<you>`.

**Comment by asvetlov** [comment]
IMHO, we should follow `docker ps`, not just `ps`.

**Comment by adavydow** [comment]
`docker` does not have multiple users. I think that not showing shared jobs by default is more reasonable, because if there is a cluster with multiple users there can be millions of public jobs.

**Comment by adavydow** [comment]
Personally I'd prefer to see my username instead of `<you>`. I do not think that this special value simplifys something + there is inconsistency: if I want to filter job by the owner, I will use username for everyone including myself.

**Comment by adavydow** [comment]
If there is a new user, who follow the tutorial and after printing `neuro ps` he sees a full screen of public jobs it's a bad experience.

**Comment by ayushkovskiy** [comment]
@adavydow:
> Personally I'd prefer to see my username instead of <you>

some users are unlucky to have long names :) So in my case, when I noticed that the column full of of `artemyushkovskiy`s in `neuro ps -a` output occupied half of my screen, I came up to the idea to replace the user's name with `<you>` (see discussion https://github.com/neuromation/platform-client-python/pull/1000#discussion_r318462987)


@mariyadavydova, with regards of your proposal:

I agree with @asvetlov to keep `neuro ps` close to `docker ps` since:
a) we still use docker images as a part of user's experience, 
b) this was the original idea to keep `neuro ps` close to `docker ps`, so changing the semantics of `neuro ps -a` will break backward compatibility. 

Perhaps, we might want to introduce a separate option `neuro ps --shared` as a filter, but this is another story and requires another issue.
