### ISSUE TITLE
Distinguish GA events from Web Terminal and local terminal

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/platform-client-python#1429]
I would like to be able to answer the following questions:

1. How many CLI commands are executed from a web terminal (a.k.a. web shell) instead of a local user machine terminal?
2. What are these commands (e.g. I would expect to see "neuro run" there, but not "neuro project")?

**Comment by dalazx** [comment]
do we log a machine's hostname? in case of the web shell it'd be job ids.

**Comment by mariyadavydova** [comment]
I guess we don't (I can't find this information).
We agreed with Andrew, that changing event category from "CLI" to "WEB-CLI" in case of running in web shell would be enough to cover my use-cases.

**Comment by dalazx** [comment]
how would we know where to change? on the web shell side we could set an env var if that helps.

**Comment by asvetlov** [comment]
The logger code is located here: https://github.com/neuromation/platform-client-python/blob/master/neuromation/cli/stats.py#L98-L114
As @mariyadavydova said, replacement `ec` (and optionally `ds`) from `CLI` to something else satisfies her needs.
I guess it could be done by an optional environment variable, the variable name doesn't matter.
This feature is useful for the web console only and should be hidden from a user. That's why we don't need CLI option or configuration parameter, only the env-var.

**Comment by anayden** [comment]
We're adding `IS_WEB_SHELL` env variable. When it's set to `1` (which is the case for webshell after https://github.com/neuromation/platform-pipelines/pull/23 is merged), neuro CLI will send events with `ec` = `WEB-CLI`, otherwise `ec` will stay `CLI`.
I don't think we should change `ds` in this case, since the data source is the same (`cli`).

**Comment by dalazx** [comment]
I'd rather go with something more generic. `NEURO_EVENT_CATEGORY`/`NEURO_EVENT_DATA_SOURCE` or whatever.

**Comment by dalazx** [comment]
say, if we will want to track `Neuro` in notebooks.

**Comment by dalazx** [comment]
plus neuro virtually knows nothing about web shell.

**Comment by anayden** [comment]
I don't think we should allow arbitrary event_category overloads with env variables.

**Comment by dalazx** [comment]
there's nothing blocking anyone from sending whatever they decide.

**Comment by anayden** [comment]
well, good point. Ok, I'll introduce `NEURO_EVENT_CATEGORY`. Still not convinced data source should be different though.

**Comment by dalazx** [comment]
@asvetlov what do you think re ^?

**Comment by asvetlov** [comment]
1. I don't care. It is *internal* API which can be changed at any moment.
In the worst case, we will get slightly incorrect statistics at the moment of switching.

2. We send *data-source* because we can and the field is enumerated in docs. I have no idea doest this filed used in our filters or not. @mariyadavydova told about *event-category* only (this field was also added without any requirement but now we are starting to utilize it).
