### ISSUE TITLE
`neuro cp` progress is not working properly without TTY

### ISSUE THREAD

**Issue by dalazx** [neuromation/platform-client-python#1498]
if I run `neuro cp` inside a job, I see no output using `neuro logs`.

running the job with `--tty` helps.

**Comment by asvetlov** [comment]
`--progress` switches the progress on for non-tty mode.
The flag is off by default.
The help text was wrong, it is fixed on master to reflect the actual behavior.
Do you want to have it always on by default?
If "yes" please describe why.
My idea was to don't pollute the output in non-tty mode like copy tools usually do. The copy of 1000 files could be very noisy otherwise.

**Comment by dalazx** [comment]
ah! :D problem solved. thanks @asvetlov
