### ISSUE TITLE
Complete support job-URI

### ISSUE THREAD

**Issue by yartem** [neuromation/platform-client-python#967]
when a job was shared, the user expects to address it via URI, however only bare job-id (or job-name) works now:
```
$ n status job://foo/job-35f32a08-7877-4ae9-bd04-5ffcebc38e15
ERROR: Failed to resolve job-name 'job://foo/job-35f32a08-7877-4ae9-bd04-5ffcebc38e15' to a job-ID: {"error": "{0: DataError(value should be None), 1: DataError(String is longer than 40 characters)}"}
ERROR: 404: Not Found
$ n status job-35f32a08-7877-4ae9-bd04-5ffcebc38e15
[OK]
```

**Comment by ayushkovskiy** [comment]
*Problem*: even though we operate with job-URIs server-side, we don't support them client-side.

*Use-case*:
- alice has job named `test-job` running,
- bob has job named `test-job` running,
- bob shares his job with alice,
- alice sees two jobs with name `test-job`, but her client automatically refers to only one of them (latest started). 

*Plan*:
Thus, we need to do the following things to fully support job URI:
1. patch api method `Jobs.list()` to send filter by owner (filtering by owner is already supported server-side)
2. patch `resolve_job()` to accept URI and use its `host` part as filter while resolving the job-name.
3. patch `parse_resource_for_sharing` to resolve `job://owner/job-name` -> `job://owner/job-ID` (see https://github.com/neuromation/platform-client-python/issues/968)
4. print job's URI somewhere in `neuro status`: otherwise it's unclear how to use them (see https://github.com/neuromation/platform-client-python/issues/968#issuecomment-524585629)
